version: '3.1'

services:

  users-db:
    image: postgres:14.2
    restart: always
    volumes:
      - ./container-data/product-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
