apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lesson2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lesson2
    spec:
      containers:
        - name: user-service
          image: spomprt/users:latest
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: datasource_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: datasource_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: datasource_password
          ports:
            - containerPort: 9999