apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lesson2
  template:
    metadata:
      labels:
        app: lesson2
    spec:
      containers:
        - name: user-service
          image: spomprt/demo:latest
          ports:
            - containerPort: 8000

