spring:
  application:
    name: users

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres

  liquibase:
    change-log: db.changelog/db.changelog-master.yml

server:
  port: 8000